#!/usr/bin/env node
/** Hubwise's pixel-art icon: one drawing, every file Android and iOS need.
 *
 * The art lives below as rows of characters, one per pixel. This writes the
 * SVGs (crisp-edged rects, so they scale like pixels) and the PNGs, which are
 * rasterised here with nearest-neighbour sampling: no rsvg or ImageMagick
 * needed, and no blurry pixel edges. Run from the repo root:
 *
 *   node tools/icons/pixel-icon.mjs
 */
import { writeFileSync } from "node:fs";
import { deflateSync } from "node:zlib";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

const palette = {
  k: "#12141a", // night background, the app's theme colour
  D: "#2a63b8", // bus outline and bumper
  B: "#4ea3ff", // bus body, the app's accent
  L: "#a9d6ff", // highlight down the left side
  W: "#dff2ff", // windscreen
  e: "#12141a", // eyes
  m: "#12141a", // smile
  p: "#ff8fb1", // cheeks
  Y: "#ffd54a", // destination sign, headlights, sparkle
  g: "#3a3f4b", // tyres
};

// The bus, facing you: mirrors out, sign lit, a face in the windscreen.
const bus = [
  "...DDDDDDDDDD...",
  "..DBYYYYYYYYBD..",
  "..DBBBBBBBBBBD..",
  "DDDLWWWWWWWWBDDD",
  "D.DLWWWWWWWWBD.D",
  "D.DLWWeWWeWWBD.D",
  "..DLWWeWWeWWBD..",
  "..DLWWWWWWWWBD..",
  "..DLWpmWWmpWBD..",
  "..DLWWWmmWWWBD..",
  "..DBBBBBBBBBBD..",
  "..DBYYBBBBYYBD..",
  "..DBBBDDDDBBBD..",
  "..DDDDDDDDDDDD..",
  "...ggg....ggg...",
  "...ggg....ggg...",
];
// ...and a sparkle, because it is on time.
const sparkle = [".Y.", "YYY", ".Y."];

/** A `size`-cell square filled with `fill`, with each [art, x, y] drawn on
 *  it, top-left corner at (x, y). */
function canvas(size, fill, layers) {
  const grid = Array.from({ length: size }, () => Array(size).fill(fill));
  for (const [art, x, y] of layers) {
    art.forEach((row, dy) => [...row].forEach((cell, dx) => {
      if (cell !== ".") grid[y + dy][x + dx] = cell;
    }));
  }
  return grid;
}

/** Knock the corners off a square to round it, in whole pixels. */
function roundCorners(grid, radius) {
  const n = grid.length;
  for (let y = 0; y < n; y++) for (let x = 0; x < n; x++) {
    const cx = x < radius ? radius - 0.5 : x >= n - radius ? n - radius - 0.5 : x;
    const cy = y < radius ? radius - 0.5 : y >= n - radius ? n - radius - 0.5 : y;
    if (Math.hypot(x - cx, y - cy) > radius) grid[y][x] = ".";
  }
  return grid;
}

// Launcher icon: the bus centred on a rounded night square.
const icon = roundCorners(canvas(22, "k", [[bus, 3, 3], [sparkle, 18, 1]]), 4);
// Maskable: full bleed, art inside the central 80% circle launchers keep.
const maskable = canvas(28, "k", [[bus, 6, 6], [sparkle, 21, 5]]);
// Status-bar badge: Android keeps only the alpha, so draw the bus solid and
// cut the windscreen out around the face.
const hollow = (art) => art.map((row) => [...row].map((c) => (c === "." || c === "W" || c === "p" ? "." : "w")).join(""));
const badge = canvas(24, ".", [[hollow(bus), 4, 5], [hollow(sparkle), 19, 1]]);
const badgePalette = { w: "#ffffff" };

function svg(grid, colours, comment) {
  const n = grid.length;
  const paths = {};
  grid.forEach((row, y) => row.forEach((cell, x) => {
    if (cell === "." || !colours[cell]) return;
    (paths[colours[cell]] ??= []).push(`M${x} ${y}h1v1h-1z`);
  }));
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${n} ${n}" shape-rendering="crispEdges">\n` +
    `  <!-- ${comment} Generated by tools/icons/pixel-icon.mjs: edit the art there. -->\n` +
    Object.entries(paths).map(([colour, d]) => `  <path fill="${colour}" d="${d.join("")}"/>`).join("\n") +
    "\n</svg>\n";
}

const crcTable = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});
function crc32(bytes) {
  let c = 0xffffffff;
  for (const b of bytes) c = crcTable[(c ^ b) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const out = Buffer.alloc(12 + data.length);
  out.writeUInt32BE(data.length, 0);
  out.write(type, 4, "ascii");
  data.copy(out, 8);
  out.writeUInt32BE(crc32(out.subarray(4, 8 + data.length)), 8 + data.length);
  return out;
}

/** Nearest-neighbour: every output pixel takes the colour of its cell. */
function png(grid, colours, size) {
  const n = grid.length;
  const raw = Buffer.alloc(size * (size * 4 + 1));
  for (let y = 0; y < size; y++) {
    const row = grid[Math.floor(y * n / size)];
    raw[y * (size * 4 + 1)] = 0; // filter: none
    for (let x = 0; x < size; x++) {
      const cell = row[Math.floor(x * n / size)];
      const hex = cell === "." ? null : colours[cell];
      const at = y * (size * 4 + 1) + 1 + x * 4;
      if (!hex) continue; // transparent
      raw[at] = parseInt(hex.slice(1, 3), 16);
      raw[at + 1] = parseInt(hex.slice(3, 5), 16);
      raw[at + 2] = parseInt(hex.slice(5, 7), 16);
      raw[at + 3] = 255;
    }
  }
  const header = Buffer.alloc(13);
  header.writeUInt32BE(size, 0);
  header.writeUInt32BE(size, 4);
  header[8] = 8; // bit depth
  header[9] = 6; // RGBA
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", header), chunk("IDAT", deflateSync(raw, { level: 9 })), chunk("IEND", Buffer.alloc(0)),
  ]);
}

const out = (path, data) => writeFileSync(join(root, path), data);
out("web/icon.svg", svg(icon, palette, "Hubwise launcher icon."));
out("tools/icons/maskable.svg", svg(maskable, palette, "Full bleed; the bus sits inside the 80% safe zone launchers crop to."));
out("tools/icons/badge.svg", svg(badge, badgePalette, "Android status-bar badge: only the alpha channel is used."));
out("web/icon-192.png", png(icon, palette, 192));
out("web/icon-512.png", png(icon, palette, 512));
out("web/icon-maskable-512.png", png(maskable, palette, 512));
out("web/apple-touch-icon.png", png(maskable, palette, 180));
out("web/badge-96.png", png(badge, badgePalette, 96));
console.log("icons written");
